### ISSUE TITLE
API token call showing owner as null after token_newowner transfer

### ISSUE THREAD

**Issue by Bushstar** [pyrkcommunity/pyrk#3]
For example the following ownership transfer.

`token_newowner 50417dfe2db111c5dc9e1a P8yUkbQERZpYri543HvXBi98wsip4xxmre`

Results in this TX.

https://explorer.pyrk.org/tx/f95e47f990104acd761901a9dc21d7bb5defd1dfaafd800f7792caee86f142c5

This is the out put in the API.

https://tokenapi.pyrk.org/api/token/50417dfe2db111c5dc9e1a

The owner address in the above API call is now null.

`"ownerAddress":null`

However when looking at the address the ownership was transferred to it is showing as the new owner.

https://tokenapi.pyrk.org/api/address/P8yUkbQERZpYri543HvXBi98wsip4xxmre

Discovered in GUI testing and confirmed in RPC call as well.

**Comment by Bushstar** [comment]
Owner address no longer shows as null, not sure if this is something that rectifies itself after a period of time or has been resolved but closing for now.

**Comment by pyrkcommunity** [comment]
This was fixed in the token backend
