### ISSUE TITLE
multiple chain-split triggerd by masternode paymentcheck

### ISSUE THREAD

**Issue by tpfuemp** [pyrkcommunity/pyrk#5]
running 3 clients for mining, one for x11, scrypt and sha256.

in the last two days multiple chain split happend leading to chain-reorgs or completly full fork.

the chainsplits are a result of failed checks of MN payments, but on the mining node the check was successfull.

example:
block found on node 1 (scrypt)
`2020-08-03 10:38:21 UpdateTip: new best=bd366c7ab43990f5897149d2f8bae73f7a12202f05c14e5d59d962f0d85c2fa3 height=74418 version=0x20000002 algo=1 (scrypt) log2_work=76.09157479 tx=107295 date='2020-08-03 10:38:18' progress=1.000000 cache=1.5MiB(11328txo)`
`2020-08-03 10:38:21 AddToWallet 846245fe299e325c90e40297d7e1b2bb73043e52a2aacf623a5dc5a27d2cee48  new`
`2020-08-03 10:38:21 ProcessNewBlock : ACCEPTED`

same block rejected on node 2 (x11):
`2020-08-03 10:38:22 CMasternodeBlockPayees::IsTransactionValid -- ERROR: Missing required payment, possible payees: 'PV7YZ6F3Fy6jx1B7ShZwz5GgtT9AYdyVpt', amount: 20.000006 PYRK`
`2020-08-03 10:38:22 IsBlockPayeeValid -- ERROR: Invalid masternode payment detected at height 74418: CTransaction(hash=846245fe29, ver=1, vin.size=1, vout.size=2, nLockTime=0)`
`    CTxIn(COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295), coinbase 03b22201041ae9275f08810005a08d0200006d696e696e6768756200fabe6d6dacb3fcb6fac5843891a365af87831e5e77daf4713487b1ce888c6e9ac9da9f0e1000000000000000, nSequence=0)`
`    CTxOut(nValue=20.00000668, scriptPubKey=76a91437c8d53d99ec26af960d2ee6)`
`    CTxOut(nValue=70.00002344, scriptPubKey=76a9147d3c5787255efc06a90c6073)`
`2020-08-03 10:38:22 ERROR: ConnectBlock(): couldn't find masternode or superblock payments`
`2020-08-03 10:38:22 InvalidChainFound: invalid block=bd366c7ab43990f5897149d2f8bae73f7a12202f05c14e5d59d962f0d85c2fa3  height=74418  log2_work=76.09157479  date=2020-08-03 10:38:18`
`2020-08-03 10:38:22 InvalidChainFound:  current best=00000000000000124c1b884b459e7b8824fa7e6b2804bbd5cec426330a6e6c22  height=74417  log2_work=76.09155878  date=2020-08-03 10:32:25`
`2020-08-03 10:38:22 ERROR: ConnectTip(): ConnectBlock bd366c7ab43990f5897149d2f8bae73f7a12202f05c14e5d59d962f0d85c2fa3 failed`

**Comment by pyrkcommunity** [comment]
we will be doing some updates soon to update these items:
DIP0002 - Special Transactions
DIP0003 - Deterministic Masternode Lists
DIP0004 - Simplified Verification of Deterministic Masternode Lists
Automatic InstantSend for "simple" transactions
Multiple improvements to PrivateSend
New Masternode Tab for DIP0003 Masternodes

**Comment by laakie** [comment]
Still seeing a lot of forks happening with 4 nodes on v0.12.4.5

**Comment by pyrkcommunity** [comment]
This issue should now be fixed in the v0.13.0 release
