### ISSUE TITLE
some pools don't pay masternodes.

### ISSUE THREAD

**Issue by kr1z1s** [pyrkcommunity/pyrk#7]
Zergpool:
https://explorer.pyrk.org/block-height/96527
https://explorer.pyrk.org/block-height/96523
https://explorer.pyrk.org/block-height/96521 and other blocks -  all coins to pool

Zpool:
https://explorer.pyrk.org/block-height/96530
https://explorer.pyrk.org/block-height/96516 and others blocks

Unknow pools
https://explorer.pyrk.org/block-height/96531
https://explorer.pyrk.org/block-height/96528 and other blocks

But for these blocks "getblocktemplate" returned required payment for the masternodes

**Comment by tpfuemp** [comment]
it's not a pool issue, masternode info from getblocktemplate is incomplete.

value "masternode_payments_enforced" is set to false 

so the question to coin maintainer is, why the corresponding spork ("SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT") is disabled

**Comment by kr1z1s** [comment]
> it's not a pool issue, masternode info from getblocktemplate is incomplete.
> 
> value "masternode_payments_enforced" is set to false
> 
> so the question to coin maintainer is, why the corresponding spork ("SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT") is disabled

Response from GBT
  "masternode_payments_started": true,
  "masternode_payments_enforced": true,

**Comment by tpfuemp** [comment]
yes, spork was disabled by coin dev during hardfork . is now been reenabled. MN payments should now again been included into blocks by all pools.

**Comment by pyrkcommunity** [comment]
Latest release now has deterministic masternodes DIP0003 and DIP0004 which should resolve this issue
