### ISSUE TITLE
0.12.4.6 build failed

### ISSUE THREAD

**Issue by laakie** [pyrkcommunity/pyrk#8]
#### If so, please list the steps to reproduce below:
1. Build failed from source.

### Expected behaviour
Building daemon and cli

### Actual behaviour
**### error: ‘const struct Consensus::Params’ has no member named ‘v3DiffChangeHeight’
error: ‘GetNextWorkRequiredV3’ was not declared in this scope
error: ‘const struct Consensus::Params’ has no member named ‘nMinActualTimespanV3’
Makefile:7027: recipe for target 'libdash_server_a-pow.o' failed**

### What version of Dash Core are you using?
0.12.4.6

### Machine specs:
- OS:    Ubuntu 16.04.5 LTS
- CPU:    Intel(R) Xeon(R) CPU E5-1660 v3 @ 3.00GHz
- RAM:  128 GB DDR4 2400 Mhz
- Disk size:  10 TB
- Disk Type (HD/SDD):  SSD

**Comment by pyrkcommunity** [comment]
Greetings..   Are you building from a git clone or from extracting the release source code zip?

**Comment by pyrkcommunity** [comment]
Those items you speak of above were fixed in the last commit, and they "should" have been included in the release.   If not, let me know and I can retag.

**Comment by laakie** [comment]
Tried both, and both have the same result

**Comment by pyrkcommunity** [comment]
ok, let me check

**Comment by pyrkcommunity** [comment]
Try now from Git clone.  I think it's missing variables in the Testnet settings.

**Comment by laakie** [comment]
Use the master branch ?

**Comment by pyrkcommunity** [comment]
yes.  or you can try the retagged release I just did

**Comment by laakie** [comment]
Yes ! that works.
Thank you 👍
