### ISSUE TITLE
runaway exception in pyrk core versions 0.12.4.5/6 on windows 7

### ISSUE THREAD

**Issue by chlorocryptos** [pyrkcommunity/pyrk#9]
### Describe the issue
When starting up Pyrk core versions 0.12.4.4 to version 0.12.4.6 the first time a runaway exception is thrown and the application does not run. The corresponding 'debug.log' entries are appended below.
From a quick search in the code base it appears that the error points to 'src/nlohmann/detail/input/parser.hpp' and 'src/nlohmann/detail/exceptions.hpp' as well as other files. 
Installation and creation of all files were processed as expected.

### Expected behaviour
If Pyrk does not run on Windows 7, it should not install or an appropiate warning should be issued...
   
### Screenshots.
![pyrk_0_12_4_5_runaway_exception_210820](https://user-images.githubusercontent.com/53777918/91080050-35533980-e645-11ea-986e-731e150d90de.jpg)

### Machine specs:
- OS: Windows 7 64 bit

### Any extra information that might be useful in the debugging process.
2020-08-24 17:53:44 GUI: Qt has caught an exception thrown from an event handler.
Throwing exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement QCoreApplication::notify() and catch all exceptions there.

EXCEPTION: N8nlohmann6detail11parse_errorE       
[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<'       C:\Pyrk\pyrk-qt.exe in Runaway exception

**Comment by pyrkcommunity** [comment]
Greetings.   Can you check if you get this error in the latest release (v0.13.0).   The package for nlohmann was upgraded in this version

**Comment by chlorocryptos** [comment]
Hi, thx for your response.
I've checked the updated 0.13.0.0 version, the error stays exactly the same, as seen in the screenshot below.
Also, the same error message appears in the 'debug.log' file (see initial post).

I'm out of the programming business for a while and I do not have knowledge about the nlohmann package,
but as the error appears to be related to a file parsing function and assuming that the application runs on linux o/s 's,
the error might be due to processing of EOL (end-of-line)/EOF (end-of-file) control chars, done differently on unix and windows
systems...
I remember though, that I've come across a similar error (but not fatal in that case) of the nlohmann package in an implementation of an IPFS (interplanetary file system) application, which does not mean the package is faulty,
but is maybe restricted in its usage to certain o/s platforms.
   
![pyrk_0_13_0_0_runaway_exception_150920](https://user-images.githubusercontent.com/53777918/93234576-c2893a00-f77c-11ea-83a6-2056cdc69569.jpg)

**Comment by Bigpiggy01** [comment]
We are not prioritizing windows 7 support since it is no longer receiving Microsoft support. You can still upgrade for free to Win 10, so I would suggest doing so especially for something you will want to secure like wallets.
